id: P000121
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །བཀའ་གདམས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - quotation
  id: SHE-SHAP-03
web_metadata:
  title:
    en: The Book of Kadam-Emanated Scriptures
    bo: བཀའ་གདམས་སྤྲུལ་པའི་གླེགས་བམ་བཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 3
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༣
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-03
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-03.epub
  description:
    en: ''
    bo: ''
